name: pub android53

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r28c-linux.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK_HOME=$(pwd)/android-ndk-r28c
      - name: Build
        run: |
          sudo chmod ugo+rwx -R ./
          export ANDROID_NDK_HOME=~/android-ndk-r28c
          ./make_android_lua53_16kb.sh
      - name: Upload53
        uses: actions/upload-artifact@v4
        with:
          path: ./plugin_lua53/**/*
          name: plugin_lua53
  publish:
    runs-on: ubuntu-latest
    needs: [android]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: plugin_lua53
          path: plugin_lua53/
      - name: Create Release Asset
        run: |
          cd plugin_lua53/ && tar cvfz ../lua53_fixFileDescriptor.tgz Plugins && cd -
      - name: Delete existing release if exists
        run: |
          gh release delete fixFileDescriptor --yes || true
          git tag -d fixFileDescriptor || true
          git push --delete origin fixFileDescriptor || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: fixFileDescriptor
          name: "fixFileDescriptor Release"
          draft: false
          prerelease: false
          files: ./lua53_fixFileDescriptor.tgz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
